# Use an official Python runtime as a parent image
FROM python:3.10-slim

WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./app .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

# Set the PYTHONPATH environment variable to include local source code
ENV PYTHONPATH=/app:$PYTHONPATH

# Set log directory
ENV FEEDBACK_LOG_DIR=/app/logs

# Expose the port the app runs on
EXPOSE 8000

# Run FastAPI when the container launches
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
